"""add_mcp_action_log

Revision ID: 0288508150f8
Revises: be74bc5b55b9
Create Date: 2026-06-20 19:37:12.185842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0288508150f8'
down_revision: Union[str, None] = 'be74bc5b55b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('inputs_json', sa.String(), nullable=True),
    sa.Column('output_json', sa.String(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('pulse_report_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_action_log_id'), 'mcp_action_log', ['id'], unique=False)
    op.create_index(op.f('ix_mcp_action_log_status'), 'mcp_action_log', ['status'], unique=False)
    op.create_index(op.f('ix_mcp_action_log_tool_name'), 'mcp_action_log', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_action_log_tool_name'), table_name='mcp_action_log')
    op.drop_index(op.f('ix_mcp_action_log_status'), table_name='mcp_action_log')
    op.drop_index(op.f('ix_mcp_action_log_id'), table_name='mcp_action_log')
    op.drop_table('mcp_action_log')
    # ### end Alembic commands ###
