"""Add nav_data table

Revision ID: 2c555f68e0c2
Revises: 
Create Date: 2026-06-19 18:47:36.569056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c555f68e0c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nav_data',
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('scheme_name', sa.String(), nullable=True),
    sa.Column('nav_value', sa.Float(), nullable=True),
    sa.Column('nav_date', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('scheme_id')
    )
    op.create_index(op.f('ix_nav_data_scheme_id'), 'nav_data', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_nav_data_scheme_name'), 'nav_data', ['scheme_name'], unique=False)
    op.create_table('triage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('query_text', sa.String(), nullable=True),
    sa.Column('bucket', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('scheme_detected', sa.String(), nullable=True),
    sa.Column('out_of_scope', sa.Boolean(), nullable=True),
    sa.Column('escalation_flag', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_log_id'), 'triage_log', ['id'], unique=False)
    op.create_index(op.f('ix_triage_log_session_id'), 'triage_log', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_log_session_id'), table_name='triage_log')
    op.drop_index(op.f('ix_triage_log_id'), table_name='triage_log')
    op.drop_table('triage_log')
    op.drop_index(op.f('ix_nav_data_scheme_name'), table_name='nav_data')
    op.drop_index(op.f('ix_nav_data_scheme_id'), table_name='nav_data')
    op.drop_table('nav_data')
    # ### end Alembic commands ###
