"""add education_articles table

Revision ID: 30ed32c89d24
Revises: ba1f09d06b9d
Create Date: 2026-06-19 20:05:12.280224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ed32c89d24'
down_revision: Union[str, None] = 'ba1f09d06b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('source_citations_json', sa.JSON(), nullable=False),
    sa.Column('last_reviewed_date', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('scheme_example_id', sa.Integer(), nullable=True),
    sa.Column('most_misunderstood', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_articles_category'), 'education_articles', ['category'], unique=False)
    op.create_index(op.f('ix_education_articles_id'), 'education_articles', ['id'], unique=False)
    op.create_index(op.f('ix_education_articles_slug'), 'education_articles', ['slug'], unique=True)
    # ### end Alembic commands ###

    # FTS5 full-text search over title + body_markdown (SQLite only — this is a dev-only
    # index; the prod Postgres migration will need an equivalent tsvector/GIN index).
    if op.get_bind().dialect.name == "sqlite":
        op.execute(
            """
            CREATE VIRTUAL TABLE education_articles_fts USING fts5(
                title, body_markdown, content='education_articles', content_rowid='id'
            )
            """
        )
        op.execute(
            """
            CREATE TRIGGER education_articles_ai AFTER INSERT ON education_articles BEGIN
                INSERT INTO education_articles_fts(rowid, title, body_markdown)
                VALUES (new.id, new.title, new.body_markdown);
            END
            """
        )
        op.execute(
            """
            CREATE TRIGGER education_articles_ad AFTER DELETE ON education_articles BEGIN
                INSERT INTO education_articles_fts(education_articles_fts, rowid, title, body_markdown)
                VALUES('delete', old.id, old.title, old.body_markdown);
            END
            """
        )
        op.execute(
            """
            CREATE TRIGGER education_articles_au AFTER UPDATE ON education_articles BEGIN
                INSERT INTO education_articles_fts(education_articles_fts, rowid, title, body_markdown)
                VALUES('delete', old.id, old.title, old.body_markdown);
                INSERT INTO education_articles_fts(rowid, title, body_markdown)
                VALUES (new.id, new.title, new.body_markdown);
            END
            """
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "sqlite":
        op.execute("DROP TRIGGER IF EXISTS education_articles_au")
        op.execute("DROP TRIGGER IF EXISTS education_articles_ad")
        op.execute("DROP TRIGGER IF EXISTS education_articles_ai")
        op.execute("DROP TABLE IF EXISTS education_articles_fts")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_education_articles_slug'), table_name='education_articles')
    op.drop_index(op.f('ix_education_articles_id'), table_name='education_articles')
    op.drop_index(op.f('ix_education_articles_category'), table_name='education_articles')
    op.drop_table('education_articles')
    # ### end Alembic commands ###
