"""add_otp_store

Revision ID: 5a6e553f6278
Revises: aa21c68b01bd
Create Date: 2026-06-19 23:49:19.713125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6e553f6278'
down_revision: Union[str, None] = 'aa21c68b01bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_store_email'), 'otp_store', ['email'], unique=False)
    op.create_index(op.f('ix_otp_store_id'), 'otp_store', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_store_id'), table_name='otp_store')
    op.drop_index(op.f('ix_otp_store_email'), table_name='otp_store')
    op.drop_table('otp_store')
    # ### end Alembic commands ###
