"""add_education_query_log_table

Revision ID: a8f5c78a952b
Revises: 0288508150f8
Create Date: 2026-06-21 13:46:51.238422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f5c78a952b'
down_revision: Union[str, None] = '0288508150f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_query_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('answer_text', sa.String(), nullable=True),
    sa.Column('bucket', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_education_query_log_id', 'education_query_log', ['id'], unique=False)
    op.create_index('ix_education_query_log_session_id', 'education_query_log', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_education_query_log_session_id', table_name='education_query_log')
    op.drop_index('ix_education_query_log_id', table_name='education_query_log')
    op.drop_table('education_query_log')
    # ### end Alembic commands ###
