"""Add FAQ models

Revision ID: ba1f09d06b9d
Revises: 2c555f68e0c2
Create Date: 2026-06-19 19:54:01.789123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1f09d06b9d'
down_revision: Union[str, None] = '2c555f68e0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_explainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('fee_term', sa.String(), nullable=True),
    sa.Column('bullets_json', sa.JSON(), nullable=True),
    sa.Column('source_links_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_explainer_fee_term'), 'fee_explainer', ['fee_term'], unique=False)
    op.create_index(op.f('ix_fee_explainer_id'), 'fee_explainer', ['id'], unique=False)
    op.create_table('session_faq_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('answer_text', sa.String(), nullable=True),
    sa.Column('bucket', sa.String(), nullable=True),
    sa.Column('scheme_name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_faq_log_id'), 'session_faq_log', ['id'], unique=False)
    op.create_index(op.f('ix_session_faq_log_session_id'), 'session_faq_log', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_faq_log_session_id'), table_name='session_faq_log')
    op.drop_index(op.f('ix_session_faq_log_id'), table_name='session_faq_log')
    op.drop_table('session_faq_log')
    op.drop_index(op.f('ix_fee_explainer_id'), table_name='fee_explainer')
    op.drop_index(op.f('ix_fee_explainer_fee_term'), table_name='fee_explainer')
    op.drop_table('fee_explainer')
    # ### end Alembic commands ###
