"""add pulse_reports and post_meeting_feedback tables

Revision ID: be74bc5b55b9
Revises: 5a6e553f6278
Create Date: 2026-06-20 07:50:45.059549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be74bc5b55b9'
down_revision: Union[str, None] = '5a6e553f6278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulse_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('top_themes_json', sa.JSON(), nullable=False),
    sa.Column('user_quotes_json', sa.JSON(), nullable=False),
    sa.Column('key_observation', sa.Text(), nullable=False),
    sa.Column('fee_spotlight_term', sa.String(), nullable=False),
    sa.Column('product_recommendations_json', sa.JSON(), nullable=False),
    sa.Column('corpus_refresh_version', sa.Integer(), nullable=True),
    sa.Column('corpus_refresh_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('sections_1_4_word_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pulse_reports_id'), 'pulse_reports', ['id'], unique=False)
    op.create_index(op.f('ix_pulse_reports_week_start_date'), 'pulse_reports', ['week_start_date'], unique=False)
    op.create_table('post_meeting_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_meeting_feedback_id'), 'post_meeting_feedback', ['id'], unique=False)
    # NOTE: autogenerate also detected the education_articles_fts* virtual tables as
    # "removed" (they're SQLite FTS5 tables created via raw SQL in an earlier migration,
    # not part of SQLAlchemy's metadata, so autogenerate always sees them as drift).
    # Deliberately NOT dropping them here — doing so would destroy the Education Hub
    # search index. See migration 30ed32c89d24 for how they're actually created/managed.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_meeting_feedback_id'), table_name='post_meeting_feedback')
    op.drop_table('post_meeting_feedback')
    op.drop_index(op.f('ix_pulse_reports_week_start_date'), table_name='pulse_reports')
    op.drop_index(op.f('ix_pulse_reports_id'), table_name='pulse_reports')
    op.drop_table('pulse_reports')
    # ### end Alembic commands ###
